# Generated by Django 4.2.1 on 2023-06-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_postauthor_post_author_comment_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Политика', 'Политика'), ('Спорт', 'Спорт'), ('Образование', 'Образование'), ('IT', 'IT')], default='Образование', max_length=64, unique=True),
        ),
    ]
