# Generated by Django 4.2.1 on 2023-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Политика', 'Политика'), ('Спорт', 'Спорт'), ('Образование', 'Образование'), ('IT', 'IT'), ('Город', 'Город')], default='Образование', max_length=64, unique=True),
        ),
    ]
