# Generated by Django 4.2.1 on 2023-06-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
